[project]
name = "posawesome"
version = "6.3.0"
description = "POS Awesome - Point of Sale for ERPNext"
authors = [
    {name = "Youssef Restom", email = "youssef@totrox.com"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPLv3"}

dependencies = [
    "qrcode[pil]>=7.3"
]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "posawesome"
